model: "runwayml/stable-diffusion-v1-5"
extended_chunks: 2
clip_penultimate: True
fp16: True
resolution: 512
seed: 42
train_text_encoder: True
lr: 1e-4
ucg: 0.1
use_ema: False
lr_scheduler: cosine
opt_betas_one: 0.9
opt_betas_two: 0.999
opt_epsilon: 1e-08
opt_weight_decay: 1e-2
buckets_shuffle: True
buckets_side_min: 256
buckets_side_max: 512
lr_scheduler_warmup: 0.05